version: "3"
services:
    react:
        image: "morant/frontend-react:version1"
        container_name: 360-new-react-app
        ports:
            - "3000:3000"
        volumes:
            - "/app/node_modules"
            - ./frontend-react:/app
    angular:
        image: "morant/frontend-angular:version1"
        container_name: 360-new-vue-angular
        ports:
            - "4200:4200"
        volumes:
            - "/app/node_modules"
            - ./frontend-angular:/app  
        environment:
            - CHOKIDAR_USEPOLLING=true