FROM node:alpine 
# A directory within the virtualized Docker (linux) environment
WORKDIR /app
COPY package*.json /app/
RUN npm install
RUN npm install -g @angular/cli@10.0.3
COPY . /app/
# Expose may be redundant here if overloaded in compose
EXPOSE 4200
CMD ["npm", "run", "start"]