FROM node:alpine
# A directory within the virtualized docker (linux) env
WORKDIR /app
COPY package*.json /app/
RUN yarn install
COPY . /app/
EXPOSE 3000
# you can just do a straight substitute of npm for yarn in FiServ
CMD ["yarn", "run", "start"]